# Generated by Django 3.1 on 2020-08-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahandle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod',
        ),
        migrations.AddField(
            model_name='product',
            name='prod',
            field=models.ManyToManyField(to='datahandle.Category'),
        ),
    ]
