# Generated by Django 3.1 on 2020-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('prod_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
